CREATE TABLE employees (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(150) NOT NULL,
	cpf CHAR(11) NOT NULL UNIQUE,
	position VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE customers (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(150) NOT NULL,
	cpf CHAR(11) NOT NULL UNIQUE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE products (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(150) NOT NULL,
	price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
	active BOOL NOT NULL DEFAULT TRUE,
	description TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	category_id BIGINT NOT NULL REFERENCES categories(id)
);

CREATE TYPE order_states AS ENUM ('PENDING', 'PAID', 'CANCELLED', 'COMPLETED');

CREATE TABLE orders (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	state order_states NOT NULL,
	total_value NUMERIC(10,2) NOT NULL CHECK (total_value >= 0),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	completed_at TIMESTAMP WITH TIME ZONE,
	customer_id BIGINT NOT NULL REFERENCES customers(id),
	employee_id BIGINT NOT NULL REFERENCES employees(id)
);

CREATE TABLE order_items (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	quantity INTEGER NOT NULL CHECK (quantity > 0),
	unit_price NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
	order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
	product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
	UNIQUE (order_id, product_id)
);

CREATE TYPE transaction_type AS ENUM ('INFLOW', 'OUTFLOW');
CREATE TYPE transaction_reason AS ENUM ('SALE', 'RETURN', 'STOCK_ADDITION', 'MANUAL_ADJUSTMENT', 'LOSS');

CREATE TABLE transactions (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	quantity INTEGER NOT NULL CHECK(quantity > 0),
	type transaction_type NOT NULL,
	reason transaction_reason NOT NULL,
	product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
	employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
	order_id BIGINT REFERENCES orders(id) ON DELETE RESTRICT
);

CREATE INDEX idx_product_name ON products(name);
CREATE INDEX idx_category_name ON categories(name);
CREATE INDEX idx_order_state ON orders(state);

CREATE INDEX idx_product_category ON products(category_id);
CREATE INDEX idx_order_customer ON orders(customer_id);
CREATE INDEX idx_order_employee ON orders(employee_id);
CREATE INDEX idx_item_order ON order_items(order_id);
CREATE INDEX idx_item_product ON order_items(product_id);
